"""Add assigned_to_id FK in tasks table

Revision ID: 87222e96154e
Revises: 89e1facdd6e3
Create Date: 2026-10-01 01:25:48.745295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87222e96154e'
down_revision: Union[str, Sequence[str], None] = '89e1facdd6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_members', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_project_member', 'project_members', ['project_id', 'user_id'])
    op.add_column('tasks', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to_id')
    op.drop_constraint('uq_project_member', 'project_members', type_='unique')
    op.alter_column('project_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_members', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
