"""chnage status and priority in Task model to not nullable

Revision ID: c3e8d1d213f8
Revises: 841a20c93b9e
Create Date: 2026-10-02 13:45:30.912503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3e8d1d213f8'
down_revision: Union[str, Sequence[str], None] = '841a20c93b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('todo', 'in_progress', 'completed', 'cancelled', name='taskstatusenum'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriorityenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriorityenum'),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('todo', 'in_progress', 'completed', 'cancelled', name='taskstatusenum'),
               nullable=True)
    # ### end Alembic commands ###
